<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="assets/php-original.svg" type="image/x-icon">
    <link rel="stylesheet" href="style.css">
    <title>ATIVIDADE 01 - PHP</title>
</head>

<body>
   
    <?php



    ?>


</body>

<main>
    <section id="content">
            <section id="alcool">
                <div id="container-comb1">
                    <h2>Álcool: </h2>
                        <div>  
                            </BR></BR>
                            <h4><strong>Olá Juliana Tudo bem? Seja bem vinda !!!</strong></h4> <br>
                        </div>
                </div>
                
            </section>
                <section id="gasoline">
                    <div id="container-comb2">
                        <h2>Gasolina :</h2>  
                            <div>  
                                </BR></BR>
                                <h4><strong>Olá Juliana Tudo bem? Seja bem vinda !!!</strong></h4> <br>
                            </div>
                    </div>
            </section>
        </section>


</main>


<footer>
    <h5>Leandro Dukiévicz R.A 21144207-5 </h5>
</footer>

</html>